[[rulesets]]
group = "REJECT"
ruleset = "rules/ACL4SSR/Clash/BanAD.list"

[[rulesets]]
group = "REJECT"
ruleset = "rules/ACL4SSR/Clash/BanEasyList.list"

[[rulesets]]
group = "REJECT"
ruleset = "rules/ACL4SSR/Clash/BanEasyListChina.list"

[[rulesets]]
group = "REJECT"
ruleset = "rules/ACL4SSR/Clash/BanEasyPrivacy.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/BanProgramAD.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/ChinaDomain.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/ChinaIp.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/ChinaMedia.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/Download.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/UnBan.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/GoogleCN.list"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "🔰 节点选择"
ruleset = "[]FINAL"



